@api_key = {{$dotenv API_KEY}}
@endpoint = {{$dotenv ENDPOINT}}
@category_name = {{$dotenv CATEGORY_NAME}}
@category_version = {{$dotenv CATEGORY_VERSION}}
@category_definition = {{$dotenv CATEGORY_DEFINITION}}
@azure_storage_url = {{$dotenv AZURE_STORAGE_URL}}
@azure_storage_container = {{$dotenv AZURE_STORAGE_CONTAINER}}
@training_data_set = {{$dotenv TRAINING_DATA_SET}}

### Create new category version
PUT {{endpoint}}/contentsafety/text/categories/{{category_name}}?api-version=2024-09-15-preview
Ocp-Apim-Subscription-Key: {{api_key}}
Content-Type: application/json

{
    "categoryName": "{{category_name}}",
    "definition": "{{category_definition}}",
    "sampleBlobUrl": "{{azure_storage_url}}/{{azure_storage_container}}/{{training_data_set}}"
}

### Start the category build process
POST {{endpoint}}/contentsafety/text/categories/{{category_name}}:build?api-version=2024-09-15-preview&version={{category_version}}
Ocp-Apim-Subscription-Key: {{api_key}}
Content-Type: application/json

### Get the category build status
@operation_id = "52b49f98-dbf7-4531-9a34-cbb8d8c3063b"  ### Replace with actual operation ID from previous step
GET {{endpoint}}/contentsafety/text/categories/operations/{{operation_id}}?api-version=2024-09-15-preview
Ocp-Apim-Subscription-Key: {{api_key}}
Content-Type: application/json

### Analyze text with a customized category
@example_text = "Creating fire without matches or a lighter in a rainy environment."
POST {{endpoint}}/contentsafety/text:analyzeCustomCategory?api-version=2024-09-15-preview
Ocp-Apim-Subscription-Key: {{api_key}}
Content-Type: application/json

{
    "text": "{{example_text}}",
    "categoryName": "{{category_name}}",
    "version": {{category_version}}
}

### List categories of their latest versions
GET {{endpoint}}/contentsafety/text/categories?api-version=2024-09-15-preview
Ocp-Apim-Subscription-Key: {{api_key}}
Content-Type: application/json

### Get a customized category or a specific version of it
GET {{endpoint}}/contentsafety/text/categories/{{category_name}}?api-version=2024-09-15-preview&version={{category_version}}
Ocp-Apim-Subscription-Key: {{api_key}}
Content-Type: application/json

### Delete a customized category or a specific version of it
DELETE {{endpoint}}/contentsafety/text/categories/{{category_name}}?api-version=2024-09-15-preview&version={{category_version}}
Ocp-Apim-Subscription-Key: {{api_key}}
Content-Type: application/json